/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const WishOutput = IDL.Record({
  'username' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const WishInput = IDL.Record({
  'username' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllWishes' : IDL.Func([], [IDL.Vec(WishOutput)], ['query']),
  'submitWish' : IDL.Func(
      [WishInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const WishOutput = IDL.Record({
    'username' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const WishInput = IDL.Record({ 'username' : IDL.Text, 'message' : IDL.Text });
  
  return IDL.Service({
    'getAllWishes' : IDL.Func([], [IDL.Vec(WishOutput)], ['query']),
    'submitWish' : IDL.Func(
        [WishInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };